### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [MatthAlex/fortran-project-template#4]
Thanks for mentioning the project on Fortran Discourse. I suggest add the topics `fortran`, `fortran-package-manager` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by MatthAlex** [comment]
Added both, plus `template` and `python`.
